name: interactive_tamil_parayana
description: Sri Ramanasramam Tamil Parayanam - Interactive


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  dynamic_text_highlighting: ^2.2.0
  audio_service: ^0.18.7
  just_audio: ^0.9.28
  device_info_plus: ^4.1.2
  android_content_provider: ^0.2.2
  permission_handler: ^10.0.0
  audioplayers: ^1.0.1
  flutter_lyric: ^2.0.4+5
  sqflite: ^2.0.2+1
  flutter_downloader: ^1.8.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  
  assets:
     - assets/images/
     - bhagavan_sitting.png
     - 11arunachala_mahatmiyam.mp3
     - tamil_parayana.db
     - 12arunachala_aksharamanamalai.mp3
     - 13arunachala_navamanimalai.mp3
     - 14arunachala_pathigam.mp3
     - 15arunachala_ashtakam.mp3
     - 16arunachala_pancharatnam.mp3
     - 17arunachala_ramanan.mp3
     - 18vazhthu.mp3


  # fonts:
  #   - family: 'Inter-Medium'
  #     fonts:
  #       - asset: assets/fonts/inter/Inter-Medium.ttf   
  